- apt:
    name: zfsutils-linux
  # Useful, but not available everywhere.
  tags: [ never, zfs ]
  become: true

- import_tasks: ddclient.yml
  tags: [ ddclient ]

- import_tasks: config.yml
  tags: [ server_config ]

