---
volumes:
  space:

networks:
  proxy-tier:
    name: proxy-tier
    external: true

services:
  app:
    image: ghcr.io/silverbulletmd/silverbullet:v2
    restart: unless-stopped
    networks:
      - proxy-tier
    env_file:
      - app.env
    volumes:
      - space:/space

