version: '3.5'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=hedgedoc
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=hedgedoc
    secrets:
      - source: postgres_password
        target: postgres_password
    volumes:
      - db13:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped

  app:
    image: quay.io/hedgedoc/hedgedoc:1.7.2
    env_file:
      - app.env
    secrets:
      - source: db_url
        target: dbURL
    volumes:
      - uploads:/hedgedoc/public/uploads
    networks:
      - default
      - proxy-tier
    restart: unless-stopped
    depends_on:
      - db

networks:
  default:
  proxy-tier:
    external:
      name: proxy-tier

secrets:
  postgres_password:
    file: ./postgres_password.secret
  db_url:
    file: ./db_url.secret

volumes:
  db13:
  uploads:
