volumes:
  vw_data:
  db17:

networks:
  proxy-tier:
    external: true
  default:
    internal: true

services:
  app:
    image: vaultwarden/server:latest
    restart: always
    ports:
      - "80"
    depends_on:
      - db
    networks:
      - default
      - proxy-tier
    volumes:
      - type: volume
        source: vw_data
        target: /data
    env_file:
      - app.env

  db:
    image: postgres:17
    restart: always
    ports:
      - "5432"
    volumes:
      - type: volume
        source: db17
        target: /var/lib/postgresql/data
    env_file:
      - db.env

