volumes:
  data:

networks:
  proxy-tier:
    external: true
  victoriametrics_vm_net:
    external: true


services:
  app:
    image: deluan/navidrome:latest
    restart: unless-stopped
    networks:
      - proxy-tier
      - victoriametrics_vm_net
    hostname: navidrome
    volumes:
      - data:/data
      - /zfast/media/Music:/music:ro
    environment:
      ND_SCANSCHEDULE: 1m
      ND_ENABLETRANSCODINGCONFIG: "true"
    env_file:
      # Change router to exclude metrics
      - app.env


