volumes:
  nextcloud:
  nextcloud_data:
  db17:

networks:
  proxy-tier:
    external: true
  default:

services:
  app:  
    hostname: nextcloud.runthejoules.info
    # Nextcloud does not support upgrades across multiple major versions.
    # Worse, it does a partial upgrade and then leaves the files neither old
    # nor new.
    image: nextcloud:30
    restart: unless-stopped
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
      - nextcloud_data:/var/www/html/data
    networks:
      - proxy-tier
      - default
    env_file:
      - db.env
      - app.env

  db:
    image: postgres:17
    restart: unless-stopped
    volumes:
      - db17:/var/lib/postgresql/data
    env_file:
      - db.env

##   collabora:
##     image: collabora/code:6.4.14.3
##     restart: unless-stopped
##     networks:
##       - default
##     ports:
##       - 9980:9980
##     cap_add:
##       - MKNOD
##     env_file:
##       - collabora.env
## 
