- name: akr - Check if present
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/bin/akr"
  register: akr_exists
  ignore_errors: yes
  changed_when: false

- import_tasks: rust.yml
  tags: [ rust ]

# Install from source because the official repo depends on an ancient version
# of libssl.
- name: akr - Download source
  when: not akr_exists.stat.exists
  git:
    repo: https://github.com/akamai/akr
    dest: /tmp/akr
    update: yes
- name: akr - Install build dependencies
  when: not akr_exists.stat.exists
  apt:
    name: pkg-config,clang,libssl-dev,make
  become: true
- name: akr - Build
  when: not akr_exists.stat.exists
  ansible.builtin.command:
    cmd: cargo build --release
    chdir: /tmp/akr
- name: akr - Copy build
  when: not akr_exists.stat.exists
  ansible.builtin.copy:
    src: /tmp/akr/target/release/akr
    dest: "{{ ansible_env.HOME }}/bin/"
