- name: git - Diff3 style
  git_config:
    name: merge.conflictstyle
    scope: global
    value: diff3
- name: git - Install ignore file
  copy:
    src: gitignore_global
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    force: no
- name: git - Configure global ignores
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_user_dir }}/.gitignore_global"
- name: tmux config
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.XDG_CONFIG_HOME }}/tmux/"
- name: vim config
  copy:
    src: vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
- name: zsh config
  copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"

