- name: git - Diff3 style
  git_config:
    name: merge.conflictstyle
    scope: global
    value: diff3
- name: git - Install ignore file
  copy:
    src: gitignore_global
    dest: "{{ ansible_user_dir }}/.gitignore_global"
    force: no
- name: git - Configure global ignores
  git_config:
    name: core.excludesfile
    scope: global
    value: "{{ ansible_user_dir }}/.gitignore_global"
- name: tmux config
  copy:
    src: tmux.conf
    dest: "{{ ansible_user_dir }}/.config/tmux/"
- name: vim config
  copy:
    src: vimrc
    dest: "{{ ansible_user_dir }}/.vimrc"
- name: zsh config
  copy:
    src: zshrc
    dest: "{{ ansible_user_dir }}/.zshrc"
- name: SSH agent
  copy:
    src: environment.d_ssh-agent.conf
    dest: "{{ ansible_user_dir }}/.config/environment.d/"
- name: SSH agent
  copy:
    src: ssh-agent.service
    dest: "{{ ansible_user_dir }}/.config/systemd/user/"

