- apt:
    name: apt-transport-https,ca-certificates,software-properties-common
  become: true

- name: Narrower distribution ID
  shell: /usr/bin/lsb_release -i -s | tr "[:upper:]" "[:lower:]"
  register: my_distribution
  changed_when: False

- name: Docker - Add signing key
  ansible.builtin.get_url:
    url: "https://download.docker.com/linux/{{ my_distribution.stdout }}/gpg"
    dest: /etc/apt/trusted.gpg.d/docker.asc
    mode: '0644'
  become: true
- name: Docker - Set up the stable repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ my_distribution.stdout }} {{ ansible_distribution_release }} stable"
  become: true

- name: Docker - Install
  apt:
    name: docker-ce,docker-compose
    # aufs-dkms is not yet supported in Raspbian.
    install_recommends: no
  become: true

- name: Docker - Create "docker" group
  group:
    name: docker
- name: Docker - Add current user to "docker" group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: true
