# https://krypt.co/developers/
- apt:
    name: software-properties-common,dirmngr,apt-transport-https
  become: true
- name: Adding KryptCo signing key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: C4A05888A1C4FA02E1566F859F2A29A569653940
  become: true
- name: Adding KryptCo repository
  apt_repository:
    repo: deb http://kryptco.github.io/deb kryptco main
  become: true
- apt:
    name: kr
  become: true
