# Install frequently-used tools for all computers.

- apt:
    name: vim,git,screen,zsh
  become: true

- import_tasks: config.yml
  tags: [ config ]

- import_tasks: docker.yml
  tags: [ docker ]

- import_tasks: akr.yml
  tags: [ akr ]

- import_tasks: podman.yml
  # Need to replace jwilder/nginx-proxy before podman can be standard.
  tags: [ never, podman ]

- name: Serial Dev - Add current user to "dialout" group
  user:
    name: "{{ ansible_user_id }}"
    groups: dialout
    append: yes
  become: true
