# Install frequently-used tools for all computers.

- apt:
    name: vim,git,screen,zsh
  become: true

- import_tasks: krypton.yml
  tags: [ krypton ]

- import_tasks: docker.yml
  tags: [ docker ]

- name: Serial Dev - Add current user to "dialout" group
  user:
    name: "{{ ansible_user_id }}"
    groups: dialout
    append: yes
