autoload -U select-word-style
select-word-style bash
setopt histignorealldups inc_append_history noshare_history

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=10000
HISTFILE=~/.zsh_history


