export PS1=$'%K{blue}%n@%m%k %W %*\n%B%F{cyan}%(4~|...|)%3~%F{white} %# %b%f%k'

autoload -U select-word-style
select-word-style bash
setopt histignorealldups inc_append_history noshare_history

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=10000
HISTFILE=~/.zsh_history


